#Add the node to inventory (/etc/hosts if there is no DNS) and copy key from master to node ssh-copy-id {server_name}
- hosts: cachenode.vmware.com
  tasks:
  - name: "Make Remote Working Directory"
    become: true
    become_user: root
    command: mkdir /tmp/cb_auto/ 
  - name: "Copy CB rpm to CB Master Server"
    become: true 
    copy:
      src: /root/filestore/cb_rpm/carbon-black-edr.rpm
      dest: /tmp/cb_auto/
  - name: "Copy CB license to CB Master Server"
    become: true 
    copy:
      src: /root/filestore/cb_rpm/carbon-black-edr.lic
      dest: /tmp/cb_auto/
  - name: "Copy the answer file to CB Master Server"
    become: true 
    copy:
      src: /root/filestore/alliance_feed_answer.txt   
      dest: /tmp/   cb_auto/   
  - name: "Install the RPM"
    become: true
    become_user: root
    shell: rpm -ivh /tmp/cb_auto/carbon-black-edr.rpm
  - name: "Update keepcache setting"
    become: yes
    become_user: root
    tags: keepcache1
    lineinfile:
      path: /etc/yum.conf
      # The String to Search
      regexp: "keepcache=0" 
      # The String to Replace
      line: "keepcache=1"
      state: present
      backup: yes    
    register: keepcache1out 
  - name: "Install the cb-enterprise"
    become: true
    become_user: root
    yum: name=cb-enterprise state=present update_cache=true 
  - name: "Tar the CB REPO"
    become: true
    become_user: root
    shell: tar -czvf /tmp/cb_auto/yumcache.tar.gz /var/cache/yum/x86_64/7/
  - name: "Fetch the yumcache.tar.gz from cache server."
    fetch:
      src: /tmp/cb_auto/yumcache.tar.gz
      dest: /root/filestore/cb_repo/    
  - name: "Configure Carbon Black EDR Server"
    become: true
    become_user: root
    command: /usr/share/cb/cbinit /tmp/cb_auto/alliance_feed_answer.txt
  - name: "Cleanup Remote Working Directory"
    become: true
    become_user: root
    command: rm -Rf /tmp/cb_auto/